### ISSUE TITLE
integrasi dengan jwt 

### ISSUE THREAD

**Issue by nurisakbar** [nurisakbar/api-haka-hotel#1]
### task

- [x] instalasi dan konfigurasi library https://github.com/tymondesigns/jwt-auth
- [x] buat api untuk register 
- [x] buat api untuk login dan melakukan return jwt

Table users : 
- id ( pk, auto increment )
- name ( string, 40 )
- email ( string, 32 nullable )
- phone ( string 18 character )
- password ( text )
- identity_number ( string,16 character, nullable )
- birth_date ( date, nullable )

### ketika register
ketika register parameter yang di input adalah : nama, nomor hp dan password
### ketika login 
ketika login yang di input adalah nomor hp saja
