### ISSUE TITLE
api untuk menambahkan fasilitas hotel

### ISSUE THREAD

**Issue by nurisakbar** [nurisakbar/api-haka-hotel#16]
setiap hotel mempunyai fasilitas yang ditawarkan kepada calon pengguna. misalnya AC, TV kabel, air panas dan lain lain.
data fasilitas ini disimpan pada tabel facilities.
sedangkan fasilitas hotel disimpan pada tabel hotel_facilities.

### TASK

- [x] buat sebuah endpoint untuk melakukan penambahkan fasilitas pada hotel
- [x] buat sebuah endoint untuk menghapus fasilitas pada endpoint

yang dikirim ketika melakukan request penambahan fasilitas adalah id fasilitas dari tabel hotel dan id hotelnya
![Screen Shot 2021-10-23 at 19 55 07](https://user-images.githubusercontent.com/5483330/138557273-d16147e8-701d-4beb-ae32-eccf40295502.png)

- [x] pastikan melakukan validasi bahwa id hotel dan id fasilitas yang di input benar benar terdapat di database, gunakan rule validasion exist seperti ketika penambahan data hotel
- [x] untuk endpoitn detlete failitasnya adalah seperti dibawah ini, dimana 1 merupakan id dari tabel facility_id
![Screen Shot 2021-10-23 at 19 56 32](https://user-images.githubusercontent.com/5483330/138557325-5274b1a3-aff6-4386-9e76-3465c0836dd0.png)
