### ISSUE TITLE
jenis kamar / room type

### ISSUE THREAD

**Issue by nurisakbar** [nurisakbar/api-haka-hotel#20]
terkadang setiap hotel mempunyai jenis kamar yang berbeda beda tergantung failitas nya.
misalnya ada kamar dengan fasilitas 2 kasur, ada juga yang cuman 1 kasur.
harga kedua jenis kamar itu juga berbeda.

## TASK

Endpoint : /api/hotel/{idhotel}/roomtype
Fungsional : CRUD

- [x] GET  | /api/hotel/{idhotel}/roomtype |  untuk menampilkan semua jenis kamar pada hotel dengan id {idhotel}
- [x] POST  | /api/hotel/{idhotel}/roomtype |  untuk menambah jenis kamar pada hotel dengan id {idhotel}
- [x] PUT  | /api/hotel/{idhotel}/roomtype/{idroomtype} |  untuk mengubah data jenis kamar pada hotel dengan id {idhotel} dan room type dengan id {idroomtype}
- [x] DELETE  | /api/hotel/{idhotel}/roomtype/{idroomtype} |  untuk menghapus data jenis kamar pada hotel dengan id {idhotel} dan room type dengan id {idroomtype}

table name :  room_type
field : id, hotel_id, name, price, description, images ( images ini sama seperti yag di hotel, bisa lebih dari 1 gambar yang nantinya akan diserialize )
