### ISSUE TITLE
Mekanisme Proses Pendaftaran

### ISSUE THREAD

**Issue by nurisakbar** [nurisakbar/api-haka-hotel#28]
proses pendaftaran akun memiliki mekanisme untuk verifikasi nomor whatapps.
jadi setelah melakukan input nama, nomor hp dan password maka sistem akan mengirimkan 4 digit angka ke nomor whatapps yang didaftarkan.

kemudian di halaman selanjutnya pengguna harus memasukan 4 digit tadi untuk melakukan verifikasi, jika nomor whatapps dan 4 digit angka yang di input cocok maka proses verifikasi berhasil.

### Task
- [ ] tambahkan fitur untuk integrasi dengan whatapps ( seperti pada project klinik )
- [ ] ketiga user melakukan register maka kirim 4 angka ke nomor whatapps user
- [ ] buat sebuah tabel baru dengan nama account_verify ( id, phone, verify_code )
- [ ] ketika proses pada point 2 dilakukan maka akan melakukan insert data ke tabel pada point nomor 3
- [ ] buat sebuah endpoint dengan nama account_verify dengan method POST ), yang di input adalah : phone_number dan verify_code. endpoint ini akan melakukan pengecekan pada tabel account_verify
- [ ] buat sebuah field baru dengan nama phone_verify_status, type data boolean, default false pada tabel users
- [ ] jika proses verifikasi berhasil maka set phone_verify_status menjadi true
